<template>
  <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
    <line
      x1="18"
      y1="6"
      x2="6"
      y2="18"
      stroke-width="2.5"
      stroke-linecap="round"
      stroke-linejoin="round"
    />
    <line
      x1="6"
      y1="6"
      x2="18"
      y2="18"
      stroke-width="2.5"
      stroke-linecap="round"
      stroke-linejoin="round"
    />
  </svg>
</template>
